apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservicea
  name: microservicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicea
  strategy:
   type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: microservicea
    spec:
      containers:
      - name: nodesource-lab-micro-a
        image: 771192296425.dkr.ecr.us-east-1.amazonaws.com/nodesource-lab-micro-a:${IMAGE_TAG}
        env:
        - name: VERSION
          value: ${RELEASE_VERSION}
        ports:
        - containerPort: 8080